
# Configuraciones de seguridad para Actuator
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.endpoints.web.base-path=/management

# Configuraciones de seguridad adicionales
server.error.include-stacktrace=never
server.error.include-message=never
spring.security.headers.frame=deny
spring.security.headers.content-type=nosniff
